# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 03:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('origin', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2)),
                ('destination', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2)),
                ('waypoints', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
