# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_route_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='template',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
