# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 19:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_route_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='waypoints',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256), size=None),
        ),
    ]
