# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161201_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
